### ISSUE TITLE
How to use GifWriteLzwImage ?

### ISSUE THREAD

**Issue by sonichy** [ginsweater/gif-h#13]
GifWriteFrame the GIF size is too big, how to use GifWriteLzwImage ?

**Comment by rversteegen** [comment]
You're probably confused. GifWriteLzwImage is not part of the public API, you should only call GifWriteFrame.

BUT if your actual question is "how can I create a .gif out of 8-bit images instead of 32-bit images", which will indeed produce smaller .gifs, then the answer is: use my fork of gif.h. I haven't filed a pull request yet back into this upstream repo. https://github.com/rversteegen/gif-h/
