### ISSUE TITLE
Resulting GIFs only have one frame

### ISSUE THREAD

**Issue by ArsenArsen** [ginsweater/gif-h#3]
Hello! I have been trying to use gif.h for GIF recording in my application. Long story short, it works, with one flaw. The first frame is the only one kept. Here is a sample result:  
![Result](https://i.arsenarsen.com/eoehksh1ep.gif)

The code I used is available here: 
```cpp
QImage &startImg = frames[0];
GifWriter writer;
GifBegin(&writer, tmpDir.absoluteFilePath("resulting.gif").toLocal8Bit().constData(), startImg.width(),
startImg.height(), d);
int i = 0;
for (QImage &a : frames) {
    QByteArray alpha8((char *)a.bits(), a.byteCount());
    GifWriteFrame(&writer, (uint8_t *)alpha8.data(), a.width(), a.height(), d);
}
GifEnd(&writer);
```

Thanks in advance!

**Comment by Wohlstand** [comment]
What value of "d" you have set?

**Comment by ArsenArsen** [comment]
`1000 / framerate`

**Comment by Wohlstand** [comment]
One thing:
1) the accepting value is in centiseconds (1/100) which is natively in GIF file format, not in milliseconds (1/1000)
2) 
I made the sample code which generates working GIF:
```cpp
#include <QApplication>
#include <QImage>
#include <QFileDialog>
#include <QList>
#include <QMessageBox>
#include "../gif.h"

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);

    QList<QImage> frames;

    QImage empty(300, 300, QImage::Format_ARGB32);
    empty.fill(0xFFFFFFFF);

    for(int i = 0; i < 15; i++)
    {
        QImage e = empty;
        e.fill(uint(rand() % 256) + (uint(rand() % 256) << 8) + (uint(rand() % 256) << 16) + (256u << 24));
        frames.push_back(e);
    }

    QString f = QFileDialog::getSaveFileName(NULL, "Spawn to", "", "GIF image (*.gif)");
    if(!f.isEmpty())
    {
        uint32_t d = 100 / 2; // Half of second per frame
        QImage &startImg = frames[0];
        GifWriter writer;
        GifBegin(&writer, f.toUtf8().constData(), (uint32_t)startImg.width(), (uint32_t)startImg.height(), d);
        //int i = 0;   //This is unused, nuke it away
        for (QImage &a : frames) {
            QByteArray alpha8((char *)a.bits(),
                  #if (QT_VERSION >= 0x050A00) //since Qt 5.10 "byteCount" will warn about deprecation
                              a.sizeInBytes() //This introduced since 5.10, so, will fail on old versions. Be careful!
                  #else
                              a.byteCount()
                  #endif
                              );
            GifWriteFrame(&writer, (uint8_t *)alpha8.data(), a.width(), a.height(), d);
        }
        GifEnd(&writer);

        QMessageBox::information(NULL, "Done!", QString("GIF Image has been wrote!"));
    }

    return 0;
}
```

![shit](https://user-images.githubusercontent.com/6751442/34320469-f1cae940-e80b-11e7-90ff-0eabace86e2d.gif)

**Comment by ArsenArsen** [comment]
Oh that's amazing. Well, thanks. But in the meanwhile I switched to avformat

**Comment by Wohlstand** [comment]
I using this library as simplest way to directly record GIF showcases from my game engine project. I plan to use the FFMPEG / AVFormat to record videos. Even with this I will still keep this simple library in use especially as lossless way to record GIF (except of color palette which is limited to 256 colors). In case of FFMPEG/AVFormat you are recording the video (obviously into lossy format) which later you converting into GIF.

**Comment by ArsenArsen** [comment]
No, actually, ffmpeg libraries allow direct gif recording with the exact same code as if it was any other format. But that's off topic here, so closing issue.

**Comment by Wohlstand** [comment]
If that, then okay. I saw some clunky usages of FFMpeg where a video file (MKV) was used as a middle storage before to generate GIF itself.
Anyway, FFMpeg itself is heavy (as lots of video and audio formats support and lot of great processing features) and using it for gif recording only is not a good solution (exception is only when you are producing software for Linux as package where ffmpeg is commonly used by many other softwares). So, this library is a choice for a small projects (for easier deployment since ffmpeg is a heavy dependency) and projects are don't needs for a wide usage of FFMpeg (if not as video player / streamer / etc., even just optionally export something into a video file rather GIF).

**Comment by ArsenArsen** [comment]
For my project the target is supporting many formats, and main target s Linux. But yes, very use case dependent

**Comment by rversteegen** [comment]
> You must feed frame writer with ARGB frames as it supports input in this only format yet.
Aside: paletted 8-bit input format is supported by this fork: https://github.com/rversteegen/gif-h

Also, in my experience the lossiness due to quantisation of 32 bit frames to 256 colours can be quite serious.

**Comment by Wohlstand** [comment]
Yeah, the result is lossy when source frame has more than 256 colors.

**Comment by rversteegen** [comment]
It's lossy even when the source frame has less than 256 colors. GifSplitPalette doesn't work very well.

**Comment by ginsweater** [comment]
Yeah, both the palettizer and the dithering have turned out quite bad in hindsight and I never got around to revisiting them. (The only advantage is they're pretty fast which is nice if you're trying to record output from a game or such.)

**Comment by rversteegen** [comment]
The dithering? It greatly improves the results, but suffers from serious bleeding. (Also, dithering is slow because it disables delta coding. In fact it's about 2x slower than pngquant in its fastest setting, and that's one of the highest quality quantisers around.)
Without dither:
![ccube_newpal](https://user-images.githubusercontent.com/1165449/34439043-188c3b7a-ed10-11e7-87c6-4a1ae3206af7.gif)
With dither:
![ccube_newpal_dither](https://user-images.githubusercontent.com/1165449/34439062-38e38f36-ed10-11e7-9119-bc37fbf28f5b.gif)

Two possible ways to fix the bleeding: firstly, diffuse less than 100% of the error. However, this generally increases contrast, though I think that's no concern when the colours are way off anyway.
I tried reducing the 7,5,3,1 coefficients in Floyd-Steinberg to 6,4,3,1, so only 87.5% of the error is diffused. (I made these numbers up, and didn't try any others.)
A comparison of normal F-S and the reduced diffusion to the original image quantised with pngquant (very close to actual original):
![ccube_newpal_dither_compare](https://user-images.githubusercontent.com/1165449/34440527-a23e243c-ed1a-11e7-8c09-f37deb9bb674.gif)

Or secondly, cap the values in the accumulation buffer to at most 255 (actually 255*256): you only clamped them above 0. (Also, scaling the accumulation buffer by 256 was probably a waste of time, considering the problems far worse than losing thousandths of a shade)

Here's a comparison of those two alternatives separately and together:
![ccube_compare_capped_88diff](https://user-images.githubusercontent.com/1165449/34440737-19d107ac-ed1c-11e7-9e1b-916fe732838c.gif)
Both separate fixes caused the average number of leaves checked while searching the palette tree to drop from 71 to 45, and combining them reduced it to 40, with a proportional speed increase too! Too bad that the fastest option, their combination, didn't give the best results.

Now, about the palette creation. @jacobly0 improved it in 704223ce63f in his branch, which I've incorporated into my own. (Should I submit a pull request? The API has changed a bit, and you'll have to take or leave the whole branch)
His improvements seemed to dramatically reduce colour bleed. In fact, all the examples I gave above were based on his changes. But here's a comparison of before and after his changes.

Before
![gif_oldpal_dither](https://user-images.githubusercontent.com/1165449/34441199-fd143a64-ed1e-11e7-9966-b889df8a9c3d.gif)
After:
![gif_newpal_dither](https://user-images.githubusercontent.com/1165449/34441201-0524f928-ed1f-11e7-899f-cb3fe75fe70b.gif)

However I don't think it helped with the problem I'm facing when dithering is disabled:
(This is 'after'. 'Before' shot omitted):
![gif_newpal](https://user-images.githubusercontent.com/1165449/34441320-c9054352-ed1f-11e7-81b3-ea5b8fa6c00c.gif)
The source sequence has 247 unique colours.
The proper solution appears to be to first select a palette and then build a k-d tree for it. Because palette creation is something like 6x faster than the dithering/thresholding step, that will probably reduce total runtime by reducing k-d leaf nodes checked. And if speed is really the priority, it's not necessary to find the best-match nearest colour.

(Thankfully github doesn't reencode gifs and seriously distort and even inflate in them process, unlike websites like gmail.)

**Comment by rversteegen** [comment]
I really should update this to say that I found out that the awful flickering results I showed in my previous comment were mostly due to bugs introduced both by my own changes and when I merged in @jacobly0's branch. Sorry!

However, even so, accumulation capping really should be used to prevent colour bleeding artifacts.

And also, it turns out that the original space partitioning implementation really is buggy (see https://github.com/rversteegen/gif-h/commit/58f80e767fdb4b8325c3b95dcc5c163455e95670), producing worse results and running slower than necessary.

But even with that fix, it's still the case that gif.h does the partitioning in a (sometimes highly) suboptimal way. If half the image is black, then half the palette is black.
To fix that I switched to a priority queue-based algorithm. I'll submit a pull request later - I need to clean it up. Unfortunately increases the code size.
